FROM debian:stable-slim

MAINTAINER Luis Perez <luis.felipe@cl.ly>

RUN apt-get update -qq && apt-get install -y apt-utils wget gnupg build-essential software-properties-common \
    python-dev python-pip zlib1g-dev libssl-dev libreadline-dev libyaml-dev libsqlite3-dev sqlite3 \
    libxml2-dev libxslt1-dev libcurl4-openssl-dev libffi-dev nodejs

RUN echo 'deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main' > /etc/apt/sources.list.d/pgdg.list && \
    wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | \
    apt-key add - \
    && apt-get update \
    && apt-get install -y libpq-dev postgresql-client-9.4

EXPOSE 3000
