version: '3'
services:
  memcached:
    image: memcached:${MEMCACHED_VERSION}
    container_name: ${CONTAINER_PREFIX}_memcached
    ports:
      - "${MEMCACHED_HOST_PORT}:11211"

  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: ${CONTAINER_PREFIX}_postgres
    volumes:
      - ${DATA_SAVE_PATH}/postgres:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"

  redis:
    image: redis:${REDIS_VERSION}
    container_name: ${CONTAINER_PREFIX}_redis
    volumes:
      - ${DATA_SAVE_PATH}/redis:/data
    ports:
      - "${REDIS_PORT}:6379"
